name = "omnipixcraft-front"
compatibility_date = "2024-01-17"
node_compat = true
[[d1_databases]]
binding = "DB"
database_name = "omnipixcraft-front"
database_id = "ffa7f665-7f4a-48b1-a7ff-b1f860892165"